version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - foodgram_network

  backend:
    image: vinnipushinka/foodgram_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - foodgram_network

  frontend:
    image: vinnipushinka/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    networks:
      - foodgram_network

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

volumes:
  postgres_data:
  static_value:
  media_value:

networks:
  foodgram_network: